Today we want to do one thing, it is find boolean function format of the S-box. Because sometimes the storage's unit mean more cost on the time. So we want a logical compose to get more fast.
How to do it that convert S-box table to logical cell ?
we find one way to do this. let's show the more detail.
Karnaugh map :
Step 1 we can get the truth table about a bit of position.
Step 2 By the truth table , we can find one of the simplest possible forms
> note : the truth table order is Gray code. more information about this way on this [link](https://en.wikipedia.org/wiki/Karnaugh_map)

the craft sbox is on the blow:

| 0  | 1  | 2  | 3 | 4  | 5  | 6  | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 |
|----|----|----|---|----|----|----|---|---|---|----|----|----|----|----|----|
| 12 | 10 | 13 | 3 | 14 | 11 | 15 | 7 | 8 | 9 | 1  | 5  | 0  | 2  | 4  | 6  |


|    | 00 | 01 | 11 | 10 |
|----|----|----|----|----|
| 00 | 0  | 4  | 12 | 8  |
| 01 | 1  | 5  | 13 | 9  |
| 11 | 3  | 7  | 15 | 11 |
| 10 | 2  | 6  | 14 | 10 |

In [63]:
table0 = [0] * 16
table1 = [0] * 16
table2 = [0] * 16
table3 = [0] * 16

sbox = [12, 10, 13, 3, 14, 11, 15, 7, 8, 9, 1, 5, 0, 2, 4, 6]
table_position = [0, 4, 12, 8,
                  1, 5, 13, 9,
                  3, 7, 15, 11,
                  2, 6, 14, 10]

import numpy as np


def get_truth_table(table: list, position: int = 0):
    for i in range(0, len(table_position)):
        if f'{sbox[table_position[i]]:04b}'[position] == '1':
            table[i] = 1
    np_table = np.array(table).reshape(4, 4)
    print(np_table)


get_truth_table(table0, 0)
get_truth_table(table1, 1)
get_truth_table(table2, 2)
get_truth_table(table3, 3)

[[1 1 0 1]
 [1 1 0 1]
 [0 0 0 0]
 [1 1 0 0]]
[[1 1 0 0]
 [0 0 0 0]
 [0 1 1 1]
 [1 1 1 0]]
[[0 1 0 0]
 [1 1 1 0]
 [1 1 1 0]
 [0 1 0 0]]
[[0 0 0 0]
 [0 1 0 1]
 [1 1 0 1]
 [1 1 0 1]]


In [88]:
# test truth table 
for i in range(0, 16):
    if ((table0[table_position[i]] << 3) + (table1[table_position[i]] << 2) + (table2[table_position[i]] << 1) + table3[table_position[i]]) != sbox[i]:
        print("truth table is error")

we let Most Significant Bit(MSB) to 0
the truth table map relation
   00 01 11 10 AB
00  1  1  0  1
01  1  1  0  1
11  0  0  0  0
10  1  1  0  0
CD
we let ABCD represent number(gray code) ,A is MSB

0-bit truth table:
   00 01 11 10 AB
00  1  1  0  1
01  1  1  0  1
11  0  0  0  0
10  1  1  0  0
CD

$f_1(A,B,C,D)=\bar{A}\bar{C}+A\bar{B}\bar{C}+\bar{A}C\bar{D}$


1-bit truth table:
   00 01 11 10 AB
00  1  1  0  0
01  0  0  0  0
11  0  1  1  1
10  1  1  1  0
CD


2-bit truth table:
   00 01 11 10 AB
00  0  1  0  0
01  1  1  1  0
11  1  1  1  0
10  0  1  0  0
CD


3-bit truth table:
   00 01 11 10 AB
00  0  0  0  0
01  0  1  0  0
11  1  1  0  1
10  1  1  0  1
CD